In [5]:
import pandas as pd
import re
import numpy as np

In [6]:
df = pd.read_json('5gPhones.json')

In [8]:
df.head(10)

,name,ram,rom,screen,front_camera,back_camera,processor,battery,price
0,"APPLE iPhone 13 (Blue, 128 GB)",None,128 GB ROM,15.49 cm (6.1 inch) Super Retina XDR Display,12MP Front Camera,12MP + 12MP,Brand Warranty for 1 Year,A15 Bionic Chip Processor,"₹58,499"
1,"vivo T2x 5G (Glimmer Black, 128 GB)",8 GB RAM,128 GB ROM,16.71 cm (6.58 inch) Full HD+ Display,8MP Front Camera,50MP + 2MP,Dimensity 6020 Processor,5000 mAh Battery,"₹15,999"
2,"vivo T2x 5G (Aurora Gold, 128 GB)",8 GB RAM,128 GB ROM,16.71 cm (6.58 inch) Full HD+ Display,8MP Front Camera,50MP + 2MP,Dimensity 6020 Processor,5000 mAh Battery,"₹15,999"
3,"vivo T2x 5G (Marine Blue, 128 GB)",6 GB RAM,128 GB ROM,16.71 cm (6.58 inch) Full HD+ Display,8MP Front Camera,50MP + 2MP,Dimensity 6020 Processor,5000 mAh Battery,"₹13,999"
4,"vivo T2x 5G (Aurora Gold, 128 GB)",4 GB RAM,128 GB ROM,16.71 cm (6.58 inch) Full HD+ Display,8MP Front Camera,50MP + 2MP,Dimensity 6020 Processor,5000 mAh Battery,"₹12,999"
5,"vivo T2x 5G (Marine Blue, 128 GB)",4 GB RAM,128 GB ROM,16.71 cm (6.58 inch) Full HD+ Display,8MP Front Camera,50MP + 2MP,Dimensity 6020 Processor,5000 mAh Battery,"₹12,999"
6,"vivo T2x 5G (Glimmer Black, 128 GB)",4 GB RAM,128 GB ROM,16.71 cm (6.58 inch) Full HD+ Display,8MP Front Camera,50MP + 2MP,Dimensity 6020 Processor,5000 mAh Battery,"₹12,999"
7,"vivo T2x 5G (Marine Blue, 128 GB)",8 GB RAM,128 GB ROM,16.71 cm (6.58 inch) Full HD+ Display,8MP Front Camera,50MP + 2MP,Dimensity 6020 Processor,5000 mAh Battery,"₹15,999"
8,"vivo T2x 5G (Glimmer Black, 128 GB)",6 GB RAM,128 GB ROM,16.71 cm (6.58 inch) Full HD+ Display,8MP Front Camera,50MP + 2MP,Dimensity 6020 Processor,5000 mAh Battery,"₹13,999"
9,"vivo T2x 5G (Aurora Gold, 128 GB)",6 GB RAM,128 GB ROM,16.71 cm (6.58 inch) Full HD+ Display,8MP Front Camera,50MP + 2MP,Dimensity 6020 Processor,5000 mAh Battery,"₹13,999"

In [9]:
df2 = df.drop(['processor'],axis=1)

In [10]:
df2.describe()

,name,ram,rom,screen,front_camera,back_camera,battery,price
count,720,637,720,720,539,720,720,720
unique,508,5,12,63,18,79,67,244
top,"SAMSUNG Galaxy M33 5G (Deep Ocean Blue, 128 GB)",8 GB RAM,128 GB ROM,16.76 cm (6.6 inch) Full HD+ Display,16MP Front Camera,50MP Rear Camera,5000 mAh Battery,"₹23,999"
freq,6,341,286,60,155,104,194,27

In [11]:
battery = df['battery']

In [103]:
battery_processed=[]
ram_processed=[]
rom_processed=[]
for bat in battery:
    s=""
    for x in bat:
        if(x.isdigit()):
            s+=x
    battery_processed.append(int(s))
for ram in df['ram']:
    try:
        s=""
        for x in ram:
            if(x.isdigit()):
                s+=x
        ram_processed.append(int(s))
    except:
        ram_processed.append(None)
for rom in df['rom']:
    s=""
    for x in rom:
        if(x.isdigit()):
            s+=x
    rom_processed.append(int(s))

In [104]:
df2['processed_battery'] = battery_processed
df2['ram_processed'] = ram_processed
df2['rom_processed'] = rom_processed

In [105]:
df2.sample(5)

,name,ram,rom,screen,front_camera,back_camera,battery,price,processed_battery,ram_processed,rom_processed
626,"IQOO Z6 Pro 5G (Phantom Dusk, 256 GB)",12 GB RAM,256 GB ROM,16.36 cm (6.44 inch) Display,None,64MP Rear Camera,4700 mAh Battery,"₹28,390",4700,12.0,256
417,"Moto G71 5G (Neptune Green, 128 GB)",6 GB RAM,128 GB ROM,16.26 cm (6.4 inch) Full HD+ AMOLED Display,16MP Front Camera,50MP + 8MP + 2MP,5000 mAh Lithium-ion Polymer Battery,"₹18,890",5000,6.0,128
243,"OnePlus Nord (Blue Marble, 128 GB)",8 GB RAM,128 GB ROM,16.36 cm (6.44 inch) Full HD+ Display,32MP + 8MP Dual Front Camera,48MP + 8MP,4115 mAh Battery,"₹25,990",4115,8.0,128
361,"POCO F3 GT 5G (Predator Black, 128 GB)",8 GB RAM,128 GB ROM,16.94 cm (6.67 inch) Full HD+ Display,16MP Front Camera,64MP + 8MP + 2MP,5065 mAh Lithium-ion Polymer Battery,"₹34,999",5065,8.0,128
337,"OPPO Reno8 5G (Shimmer Gold, 128 GB)",8 GB RAM,128 GB ROM,16.33 cm (6.43 inch) Full HD Display,32MP Front Camera,50MP + 8MP + 2MP,4500 mAh Lithium-ion Polymer Battery,"₹29,999",4500,8.0,128

In [106]:
df3 = df2[df2['processed_battery'] >= 4000]

In [107]:
df3 = df3[df3['rom_processed']>=32]
df3 = df3[df3['ram_processed']>=2]

In [108]:
backcam = []
for cam in df3['back_camera']:
    s=""
    for j in cam.split()[0]:
        if(j.isdigit()):
            s+=j
    backcam.append(int(s))

In [109]:
df3['back_camera_processed'] = backcam

In [110]:
frontcam = []
for cam in df3['front_camera']:
    
    try:
        s=""
        for j in cam.split()[0]:
            if(j.isdigit()):
                s+=j
        frontcam.append(int(s))
    except:
        frontcam.append(None)

In [111]:
len(frontcam), len(df3['front_camera'].to_list())

(618, 618)

In [112]:
df3['front_camera_processed'] = frontcam

In [113]:
screen=[]
for scr in df3['screen']:
    
    screen.append(float(scr.split()[0]))

In [114]:
df3['screen_processed'] = screen

In [115]:
brand = []
for n in df3['name']:
    s=n.split()[0]
    brand.append(s)

In [121]:
df3['brand'] = brand

In [128]:
price=[]
for p in df3['price']:
    
    s = re.sub(r"[^a-zA-Z0-9 ]", "", p)
    price.append(int(s))

In [131]:
df3['price_processed'] = price

In [132]:
final_df = df3.drop(['ram','rom','screen','battery','front_camera','back_camera','price'],axis=1)

In [133]:
final_df.describe()

,processed_battery,ram_processed,rom_processed,back_camera_processed,front_camera_processed,screen_processed,price_processed
count,618.000000,618.00000,618.000000,618.000000,440.000000,618.000000,618.000000
mean,5077.682848,7.87055,161.553398,61.106796,21.765909,16.859984,30103.035599
std,3162.028533,2.29072,66.399663,30.231118,15.063184,1.468116,17702.094928
min,4000.000000,4.00000,64.000000,5.000000,8.000000,15.490000,11499.000000
25%,4500.000000,6.00000,128.000000,50.000000,13.000000,16.640000,18124.000000
50%,5000.000000,8.00000,128.000000,50.000000,16.000000,16.760000,25999.000000
75%,5000.000000,8.00000,256.000000,64.000000,32.000000,17.020000,34999.000000
max,50000.000000,16.00000,512.000000,200.000000,108.000000,41.940000,164989.000000

In [134]:
final_df.sample(5)

,name,processed_battery,ram_processed,rom_processed,back_camera_processed,front_camera_processed,screen_processed,brand,price_processed
540,"SAMSUNG Galaxy S23 Ultra 5G (Cream, 256 GB)",5000,12.0,256,200,12.0,17.27,SAMSUNG,124999
588,"OnePlus 9 Pro 5G (Stellar Black, 256 GB)",4500,12.0,256,48,NaN,17.02,OnePlus,64999
224,"REDMI Note 12 Pro+ 5G (Obsidian Black, 256 GB)",4980,12.0,256,200,16.0,16.94,REDMI,32999
110,"REDMI Note 12 Pro 5G (Glacier Blue, 128 GB)",5000,6.0,128,50,16.0,16.94,REDMI,23999
33,"Infinix Note 12 Pro 5G (Snowfall, 128 GB)",5000,8.0,128,108,16.0,17.02,Infinix,15999

In [135]:
final_df.to_json("5gPhones_Cleaned.json")

In [ ]:
final_df = pd.read